fruits=["apple","banans","cherry","orange","mango"]
fruits[2]="null"
print(fruits)
fruits[2:5]=["null","null"]
print(fruits)
fruits[1:2]=["cha","kka"]
print(fruits)
fruits=["apple","banans","cherry","orange","mango"]
fruits[1:2]=["cha","kka"]
print(fruits)
fruits=["apple","banans","cherry","orange","mango"]
fruits[1:3]=["plums"]
print(fruits)
fruits=["apple","banans","cherry","orange","mango"]
fruits.insert(2,"plums")
print(fruits)
fruits=["apple","banans","cherry","orange","mango"]
fruits.append("null")
print(fruits)
fruits=["apple","banans","cherry","orange","mango"]
flowers=["sunflower","jamandhi","hibiscous"]
fruits.extend(flowers)
print(fruits)
flowers.extend(fruits)
print(flowers)
flowers=["sunflower","jamandhi","hibiscous"]
tuple=("kiwi","plums")
flowers.extend(tuple)
print(flowers)