fruits=["apple","banana","cherry"]
print(fruits)
fruits=["apple","banana","cherry","banana"]
print(fruits)
print(len(fruits))
list1=["apple","banana","cherry"]
list2=[1,2,3,4,5]
list3=[True,False,False]
print(list1)
print(list2)
print(list3)
list4=["abc",34,True]
print(list4)
fruits=["apple","banana","cherry"]
print(type(fruits))
list2=[1,2,3,4,5]
print(type(list2))
list3=[True,False,False]
print(type(list3))
fruits=list(("apple","banana","cherry"))
print(fruits)
